import Head from "next/head";
import Image from "next/image";
import { ReactElement } from "react";
import SearchInput from "../components/Search/SearchInput";
import IndexLayout from "../layouts/IndexLayout";
import styles from "../styles/Home.module.css";
import { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Movie Website by Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchInput />
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <IndexLayout>{page}</IndexLayout>;
};

export default Home;
